language: node_js
node_js:
  - "10"
  - "12"

script:
  - npm run lint
  - npm run test:unit

after_success:
  - npm run build

deploy:
  provider: npm
  skip_cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true

notifications:
  email:
    recipients:
      - victorfranlopes@outlook.com
      - coder.marcos@gmail.com
    on_success: change
    on_failure: always